import { useLanguageContext } from "../components/language-provider"

const translations = {
  EN: {
    "select.language-placeholder": "Choose your language",
    "select.default": "Select",
    "select.no-options-message": "Language not available",
    index: "Index",
    "pricing.cloud.google": "GCP",
    "related.resources.section":
      "Sign up and get instant access to these additional eBooks.",
    All: "All",
    Blog: "Blog",
    "list.separator": ", ",
    "list.last-separator": " and ",
    "general.next": "Next",
    "general.all": "All",
    "general.previous": "Previous",
    "general.page-number": "Page %pageNumber%",
    "general.page": "Page",
    "general.home": "Home",
    "general.site-search": "Site search",
    "general.language-switch": "Switch language. Current Language - ",
    "general.showing-results": "Showing %results% of %total% results",
    "general.showing-customers": "Showing %results% of %total% customers",
    "general.showing-demos": "Showing %results% of %total% demos",
    "general.showing-events": "Showing %results% of %total% events",
    "general.no-results-filters":
      "No results available. Try adjusting the filters or start a new search.",
    "general.reset-list": "reset the list",
    "general.explore-the-case-study": "Explore the case study",
    "general.clear-all": "clear all",
    "general.sort": "Sort",
    "general.industry": "Industry",
    "general.region": "Region",
    "general.platform": "Platform",
    "general.product": "Product",
    "general.difficulty": "Difficulty",
    "general.cloud": "Cloud",
    "general.solution": "Solution",
    "general.tech-partner": "Tech Partner",
    "general.skip-to-main-content": "Skip to main content",
    "general.learn-more": "Learn more",
    "blog.seo.title": "Databricks Blog",
    "blog.seo.description":
      "Get product updates, Apache Spark best-practices, use cases, and more from the Databricks team.",
    "blog.related.title": "Related posts",
    "blog.related.cta": "See all %category% posts",
    "blog.try-free.body": "Try Databricks for free",
    "blog.try-free.cta": "Get Started",
    "blog.head.author-prefix": `by `,
    "blog.head.author-suffix": "",
    "blog.head.meta": `in`,
    "blog.head.share": `Share this post`,
    "blog.category.empty":
      "No blog is available in this category. Please choose other categories.",
    "footer.language.title": "Worldwide",
    "legal.header": "Legal",
    "form.first-name": "First name",
    "form.last-name": "Last name",
    "form.full-name": "Full name",
    "form.company": "Company",
    "form.company-email": "Email",
    "form.country": "Country",
    "form.phone": "Phone",
    "form.phone-optional": "Phone (Optional)",
    "form.phone-input": "Phone Number",
    "form.contact-reason": "Contact Reason",
    "form.contact-sales": "Contact Sales",
    "form.databricks-products-features-and-capabilities":
      "Databricks Products, Features and Capabilities",
    "form.technical-support-for-existing-customers":
      "Technical Support for Existing Customers",
    "form.events-and-webinars": "Events and Webinars",
    "form.press-analyst-inquiry": "Press / Analyst Inquiry",
    "form.training-courses-and-certification": "Training Courses and Certification",
    "form.request-demo": "Request Demo",
    "form.job-title": "Job Title",
    "form.title": "Title",
    "form.where-do-you-intend-to-run-your-analytic-workloads?":
      "Where do you intend to run your analytic workloads?",
    "form.aws": "AWS",
    "form.azure": "Azure",
    "form.google-cloud-platform": "Google Cloud Platform",
    "form.on-premise": "On-Premise",
    "form.other": "Other",
    "form.message": "Message",
    "form.keep-me-informed-with-occasional-updates-about-databricks-and-related-open-source-products":
      "Keep me informed with occasional updates about Databricks and related open source products",
    "form.submit": "Submit",
    "form.please-wait": "Please wait",
    "form.select": "Select...",
    "form.this-field-is-required": "* This field is required.",
    "form.must-be-valid-email.": "Must be valid email.",
    "form.get-started": "Get Started",
    "form.choose-a-cloud-provider": "Choose a cloud provider",
    "customer.taxonomy.industry": "INDUSTRY:",
    "customer.taxonomy.platform": "PLATFORM USE CASE:",
    "customer.taxonomy.cloud": "CLOUD:",
    "pricing.plan.selector": "Select plan",
    "pricing.plan.helper": "help me choose",
    "pricing.plan.standard": "Standard",
    "pricing.plan.premium": "Premium",
    "pricing.plan.enterprise": "Enterprise",
    "pricing.cloud.selector": "Select cloud",
    "pricing.cloud.azure": "Azure",
    "pricing.cloud.aws": "AWS",
    "pricing.cloud.gcp": "Google Cloud",
    "pricing.region.selector": "Select region",
    "pricing.region.selector.description":
      "(refer to FAQ below for product availability)",
    "pricing.region.serverless": "region with serverless SQL & SQL Pro",
    "pricing.region.us-east": "US East (N. Virginia)",
    "pricing.region.us-east-2": "US East (Ohio)",
    "pricing.region.us-west": "US West (Oregon)",
    "pricing.region.europe": "Europe (Frankfurt)",
    "pricing.region.europe-2": "Europe (Ireland)",
    "pricing.region.apac": "AP (Sydney)",
    "customer.taxonomy.solution": "SOLUTION:",
    "form.form-title": "Create your Databricks account",
    "form.submit-text": "Continue",
    "form.error-required": "This field is required",
    "form.error-loading": "Loading...",
    "form.error-error": "An error has occurred. Please try again later.",
    "form.error-email-error":
      "We cannot create an account with the email address you provided. If you have used this email in the past, try the 'Forgot Password?' link on the Databricks <a href='https://accounts.cloud.databricks.com/registration'>login page</a> or <a href='https://www.databricks.com/company/contact'>contact our sales team.</a>",
    "form.error-field-phone": "Please enter a valid phone number",
    "form.error-field-email": "Please enter a valid email address",
    "form.cumminity-edition-title": "Don't have a cloud account?",
    "form.cumminity-edition-text":
      "Community Edition is a limited Databricks environment for personal use and training.",
    "form.cumminity-edition-get-started": "Get started with Community Edition",
    "form.cumminity-edition-get-started-agreement":
      "By clicking “Get started with Community Edition,” you agree to the",
    "form.and": "and",
    "form.privacy-policy": "Privacy Policy",
    "form.terms-of-service": "Terms of Service",
    "form.get-started-agreement": "By clicking “Get Started,” you agree to the ",
    "partners.load-more": "Load More",
    "partners.filters.region": "Region",
    "partners.filters.industry": "Industry",
    "partners.filters.use-cases": "Use cases",
    "partners.filters.partner": "Partner",
    "demo.filters.demo-type": "Demo Type",
    "demo.filters.product": "Product",
    "demo.filters.platform": "Platform",
    "glossary.back-to-glossary": "Back to Glossary",
    "glossary.additional-resources": "Additional Resources",
    "events-overview.cards.cta-label": "Event Details",
    "events-overview.cards.section-title": "Browse All Upcoming Events",
    "events-overview.cards.event-type": "Event Type",
    "resources-overview.resource-type": "Resource Type",
    "solutions-accelerators.sort.alphabetical": "A-Z",
    "solutions-accelerators.sort.newest": "Newest first",
    "solutions-accelerators.sort.popular": "Most popular",
    "general.youtube-privacy-accept":
      "To play this video, click here and accept cookies",
    "research.filter.research-domain": "Research Domain",
    "card.featured": "Featured",
    "card.tag.recommended": "Recommended",
    "pdf.error": "Failed to load PDF file.",
    "general.search": "search",
    "general.newest": "Newest",
    "general.subscribe-to-newsletter": "Subscribe to Newsletter",
    "featured.stories": "Featured Stories",
    "more.headlines": "More Headlines",
    "press.releases": "Press Releases",
    "press.releases.see.all": "See all press releases",
    "press.releases.see.more": "See more",
    "resources.title": "Resources",
    "resources.contact.title": "Contact",
    "resources.inquires": "For press inquires:",
    "resources.stay.connected": "Stay connected",
    "resources.stay.connected.description":
      "Stay up to date and connect with us through our newsletter, social media channels and blog RSS feed.",
    "resources.subscribe": "Subscribe to the newsletter",
    "resources.get": "Get assets",
    "resources.contact.description":
      "If you would like to use Databricks materials, please contact <u><a href='mailto: brand@databricks.com'>brand@databricks.com</a></u> and provide the following information:",
    "resources.contact.info":
      "Your name and title<br />Company name and location<br />Description of request",
    "resources.contact.guidelines": "View brand guidelines",
    "general.others": "Others",
  },
  FR: {
    "general.clear-all": "effacer les filtres",
    "general.sort": "Trier",
    "general.showing-results": "Affichage de %results% sur %total% des résultats",
    "general.skip-to-main-content": "Revenir au contenu principal",
    "select.language-placeholder": "Choisissez votre langue",
    "select.default": "Sélectionner",
    "select.no-options-message": "Langue non disponible",
    "general.next": "Suivant",
    "blog.seo.description":
      "Recevez des informations sur les produits, des bonnes pratiques pour Apache Spark, des exemples d'utilisation et bien plus, directement de l'équipe de Databricks.",
    "blog.related": "Articles connexes",
    "blog.try-free.body": "Essayer Gratuitement Databricks",
    "blog.try-free.cta": "Démarrer",
    "blog.description": "Les dernières nouvelles et articles de Databricks",
    "footer.language.title": "pays/régions",
    "form.first-name": "Prénom",
    "form.last-name": "Nom",
    "form.full-name": "Nom complet",
    "form.company": "Entreprise",
    "form.company-email": "E-mail professionnel",
    "form.country": "Pays",
    "form.phone": "Téléphone",
    "form.phone-optional": "Numéro de téléphone (facultatif)",
    "form.contact-reason": "Motif de la prise de contact",
    "form.contact-sales": "Contact commercial",
    "form.databricks-products-features-and-capabilities":
      "Produits Databricks, caractéristiques et fonctionnalités",
    "form.technical-support-for-existing-customers":
      "Support technique pour clients existants",
    "form.events-and-webinars": "Événements et webinars",
    "form.press-analyst-inquiry": "Demande presse / analystes",
    "form.training-courses-and-certification": "Formation et certification",
    "form.request-demo": "Demande de démo",
    "form.job-title": "Intitulé de poste",
    "form.title": "Intitulé de poste",
    "form.where-do-you-intend-to-run-your-analytic-workloads?":
      "Où souhaitez-vous exécuter vos charges de travail analytiques ?",
    "form.aws": "AWS",
    "form.azure": "Azure",
    "form.google-cloud-platform": "Google Cloud Platform",
    "form.on-premise": "Sur site (on-premise)",
    "form.other": "Autre",
    "form.message": "Message",
    "form.keep-me-informed-with-occasional-updates-about-databricks-and-related-open-source-products":
      "Tenez-moi au courant des mises à jour ponctuelles concernant Databricks et les produits open source associés",
    "form.submit": "Valider",
    "form.please-wait": "Merci de patienter",
    "form.select": "Veuillez sélectionner",
    "form.this-field-is-required": "Champ obligatoire.",
    "form.must-be-valid-email.": "S'il vous plaît, mettez une adresse email valide.",
    "form.get-started": "Get Started",
    "form.choose-a-cloud-provider": "Sélectionnez un fournisseur de cloud",
    "pricing.plan.selector": "Sélectionnez un plan",
    "pricing.plan.helper": "Aidez-moi à choisir",
    "pricing.plan.standard": "Standard",
    "pricing.plan.premium": "Premium",
    "pricing.plan.enterprise": "Entreprise",
    "pricing.cloud.selector": "Sélectionnez un cloud",
    "pricing.cloud.azure": "Azure",
    "pricing.cloud.aws": "AWS",
    "pricing.cloud.gcp": "Google Cloud",
    "pricing.region.selector": "Sélectionnez une région",
    "pricing.region.selector.description":
      "(voir FAQ ci-dessous pour la disponibilité des produits)",
    "pricing.region.serverless": "Région avec SQL sans serveur et SQL Pro",
    "pricing.region.us-east": "États-Unis Est (Virginie du N.)",
    "pricing.region.us-east-2": "États-Unis Est (Ohio)",
    "pricing.region.us-west": "États-Unis Ouest (Oregon)",
    "pricing.region.europe": "Europe (Francfort)",
    "pricing.region.europe-2": "Europe (Irlande)",
    "pricing.region.apac": "AP (Sydney)",
    "form.form-title": "Créez votre compte Databricks",
    "form.submit-text": "Continuer",
    "form.error-required": "Champ obligatoire.",
    "form.error-loading": "Chargement...",
    "form.error-error":
      "Une erreur est survenue, veuillez réessayer ultérieurement.",
    "form.error-email-error":
      "Nous ne parvenons pas à créer un compte avec l'adresse e-mail que vous avez fournie. Si vous avez déjà utilisé cet e-mail par le passé, essayer le mécanisme en cas d'oubli de mot de passe sur la <a href='https://accounts.cloud.databricks.com/registration.html#login'>page de connexion</a> de Databricks, ou bien <a href='https://www.databricks.com/fr/company/contact'>contactez notre équipe commerciale</a> pour obtenir de l'aide.",
    "form.error-field-phone": "Veuillez saisir un numéro de téléphone valide",
    "form.error-field-email": "Veuillez saisir une adresse e-mail valide",
    "form.cumminity-edition-title": "Vous n’avez pas de compte cloud ?",
    "form.cumminity-edition-text":
      "Community Edition est un environnement Databricks limité destiné à un usage personnel et à la formation.",
    "form.cumminity-edition-get-started": "Essayer Community Edition",
    "form.cumminity-edition-get-started-agreement":
      "En cliquant sur « Essayer Community Edition », vous acceptez la",
    "form.and": "et les",
    "form.privacy-policy": "Politique de confidentialité",
    "form.terms-of-service": "Conditions de service",
    "form.get-started-agreement": "En cliquant sur « Essayer », vous acceptez la ",
    "partners.load-more": "LIRE PLUS",
    "partners.filters.region": "Région",
    "partners.filters.use-cases": "Cas d'usage",
    "partners.filters.partner": "Partenaires",
    "general.explore-the-case-study": "Explorez l'étude de cas",
    "general.learn-more": "En savoir plus",
    "general.youtube-privacy-accept":
      "Pour lire cette vidéo, cliquez ici et acceptez les cookies",
    "glossary.back-to-glossary": "Retour au glossaire",
    "glossary.additional-resources": "Ressources complémentaires",
    "research.filter.research-domain": "Domaine de recherche",
    "resources-overview.resource-type": "Type de ressource",
    "general.newest": "Nouveau",
    "general.subscribe-to-newsletter": "Abonnez-vous à la newsletter",
    "card.featured": "En vedette",
    "general.search": "rechercher",
    "demo.filters.product": "Produit",
    "demo.filters.demo-type": "Type de démo",
    "card.tag.recommended": "recommandé",
    "pdf.error": "Échec du chargement du fichier PDF.",
    "featured.stories": "Featured Stories",
    "more.headlines": "More Headlines",
    "press.releases": "Press Releases",
    "press.releases.see.all": "See all press releases",
    "press.releases.see.more": "See more",
    "resources.title": "Resources",
    "resources.contact.title": "Contact",
    "resources.inquires": "For press inquires:",
    "resources.stay.connected": "Stay connected",
    "resources.stay.connected.description":
      "Stay up to date and connect with us through our newsletter, social media channels and blog RSS feed.",
    "resources.subscribe": "Subscribe to the newsletter",
    "resources.get": "Get assets",
    "resources.contact.description":
      "If you would like to use Databricks materials, please contact <u><a href='mailto: brand@databricks.com'>brand@databricks.com</a></u> and provide the following information:",
    "resources.contact.info":
      "Your name and title<br />Company name and location<br />Description of request",
    "resources.contact.guidelines": "View brand guidelines",
  },
  DE: {
    "general.search": "suchen",
    "general.newest": "Neueste",
    "general.clear-all": "filter löschen",
    "general.sort": "Sortieren",
    "general.showing-results": "%results% der %total%-Ergebnisse werden angezeigt",
    "general.skip-to-main-content": "Direkt zum Hauptinhalt",
    "select.language-placeholder": "Wählen Sie Ihre Sprache",
    "select.no-options-message": "Sprache nicht verfügba",
    "select.default": "Wählen",
    "general.next": "Weiter",
    "blog.seo.description":
      "Produkt-Updates, Best Practices für Apache Spark, Anwendungsfälle und mehr erhalten Sie vom Databricks-Team.",
    "blog.try-free.body": "DATABRICKS KOSTENLOS TESTEN",
    "blog.try-free.cta": "Erste Schritte",
    "footer.language.title": "Weltweit",
    "form.first-name": "Vorname",
    "form.last-name": "Nachname",
    "form.full-name": "Vollständiger Name",
    "form.company": "Unternehmen",
    "form.company-email": "Berufliche E-Mail-Adresse",
    "form.country": "Land",
    "form.phone": "Rufnummer",
    "form.phone-optional": "Rufnummer (Optional)",
    "form.contact-reason": "Grund für die Kontaktaufnahme",
    "form.contact-sales": "Kontaktaufnahme mit Vertrieb",
    "form.databricks-products-features-and-capabilities":
      "Produkte, Merkmale und Funktionen von Databricks",
    "form.technical-support-for-existing-customers":
      "Technischer Support für Bestandskunden",
    "form.events-and-webinars": "Veranstaltungen und Webinare",
    "form.press-analyst-inquiry": "Presse-/Analystenanfrage",
    "form.training-courses-and-certification": "Schulungen und Zertifizierungen",
    "form.request-demo": "Demo anfordern",
    "form.job-title": "Stellenbezeichnung",
    "form.title": "Stellenbezeichnung",
    "form.where-do-you-intend-to-run-your-analytic-workloads?":
      "Wo möchten Sie Ihre Analyse-Workloads ausführen?",
    "form.aws": "AWS",
    "form.azure": "Azure",
    "form.google-cloud-platform": "Google Cloud Platform",
    "form.on-premise": "On-Premises",
    "form.other": "Sonstiges",
    "form.message": "Nachricht",
    "form.keep-me-informed-with-occasional-updates-about-databricks-and-related-open-source-products":
      "Bitte senden Sie mir gelegentlich aktuelle Informationen zu Databricks und zugehörigen Open-Source-Produkten.",
    "form.submit": "Übermitteln",
    "form.please-wait": "Bitte warten",
    "form.select": "Bitte auswählen",
    "form.this-field-is-required": "Dies ist ein Pflichtfeld.",
    "form.must-be-valid-email.": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "form.get-started": "Get Started",
    "form.choose-a-cloud-provider": "Cloud-Anbieter auswählen",
    "pricing.plan.selector": "Tarif auswählen",
    "pricing.plan.helper": "Hilfe bei der Auswahl",
    "pricing.plan.standard": "Standard",
    "pricing.plan.premium": "Premium",
    "pricing.plan.enterprise": "Enterprise",
    "pricing.cloud.selector": "Cloud auswählen",
    "pricing.cloud.azure": "Azure",
    "pricing.cloud.aws": "AWS",
    "pricing.cloud.gcp": "Google Cloud",
    "pricing.region.selector": "Region auswählen",
    "pricing.region.selector.description":
      "(siehe FAQ unten für Produktverfügbarkeit)",
    "pricing.region.serverless": "Region mit serverlosem SQL & SQL Pro",
    "pricing.region.us-east": "USA Ost (Nord-Virginia)",
    "pricing.region.us-east-2": "USA Ost (Ohio)",
    "pricing.region.us-west": "USA West (Oregon)",
    "pricing.region.europe": "Europa (Frankfurt)",
    "pricing.region.europe-2": "Europa (Irland)",
    "pricing.region.apac": "Asien-Pazifik (Sydney)",
    "form.form-title": "Erstellen Sie Ihr Databricks-Konto",
    "form.submit-text": "Fortsetzen",
    "form.error-required": "Dies ist ein Pflichtfeld.",
    "form.error-loading": "Wird geladen …",
    "form.error-error":
      "Ein Fehler ist aufgetreten. Bitte versuchen Sie es später noch einmal.",
    "form.error-email-error":
      "Wir können mit der von Ihnen angegebenen E-Mail-Adresse kein Konto erstellen. Wenn Sie diese E-Mail in der Vergangenheit bereits verwendet haben, können Sie versuchen, die Funktion „Passwort vergessen“ auf der <a href='https://accounts.cloud.databricks.com/registration.html#login'>Databricks-Anmeldeseite</a> zu nutzen, oder <a href='https://www.databricks.com/de/company/contact'>Sie setzen sich mit unserem Vertriebsteam in Verbindung</a>.",
    "form.error-field-phone": "Bitte geben Sie eine gültige Telefonnummer ein",
    "form.error-field-email": "Bitte geben Sie eine gültige E-Mail Adresse ein",
    "form.cumminity-edition-title": "Sie haben kein Cloud-Konto?",
    "form.cumminity-edition-text":
      "Die Community Edition ist eine eingeschränkte Databricks-Umgebung für die persönliche Nutzung und Schulung.",
    "form.cumminity-edition-get-started": "Erste Schritte mit der Community Edition",
    "form.cumminity-edition-get-started-agreement":
      "Indem Sie auf „Erste Schritte mit der Community Edition“ klicken, erklären Sie sich mit den",
    "form.and": "und",
    "form.privacy-policy": "Datenschutzbestimmungen",
    "form.terms-of-service": "Nutzungsbedingungen einverstanden",
    "form.get-started-agreement":
      "Durch Klicken auf „Jetzt loslegen“ erklären Sie sich mit der ",
    "partners.load-more": "MEHR LADEN",
    "partners.filters.region": "Region",
    "partners.filters.use-cases": "Anwendungsfälle",
    "partners.filters.partner": "Partner",
    "general.explore-the-case-study": "Erkunden Sie die Fallstudie",
    "general.learn-more": "Mehr Informationen",
    "general.youtube-privacy-accept":
      "Um dieses Video abzuspielen, klicken Sie hier und akzeptieren Sie Cookies",
    "glossary.back-to-glossary": "Zurück zum Glossar",
    "glossary.additional-resources": "Zusätzliche Ressourcen",
    "research.filter.research-domain": "Forschungsbereich",
    "resources-overview.resource-type": "Ressourcentyp",
    "demo.filters.product": "Produkt",
    "demo.filters.demo-type": "Demo-Typ",
    "general.subscribe-to-newsletter": "Newsletter abonnieren",
    "card.featured": "Hervorgehoben",
    "card.tag.recommended": "empfohlen",
    "pdf.error": "PDF-Datei konnte nicht geladen werden.",
    "featured.stories": "Featured Stories",
    "more.headlines": "More Headlines",
    "press.releases": "Press Releases",
    "press.releases.see.all": "See all press releases",
    "press.releases.see.more": "See more",
    "resources.title": "Resources",
    "resources.contact.title": "Contact",
    "resources.inquires": "For press inquires:",
    "resources.stay.connected": "Stay connected",
    "resources.stay.connected.description":
      "Stay up to date and connect with us through our newsletter, social media channels and blog RSS feed.",
    "resources.subscribe": "Subscribe to the newsletter",
    "resources.get": "Get assets",
    "resources.contact.description":
      "If you would like to use Databricks materials, please contact <u><a href='mailto: brand@databricks.com'>brand@databricks.com</a></u> and provide the following information:",
    "resources.contact.info":
      "Your name and title<br />Company name and location<br />Description of request",
    "resources.contact.guidelines": "View brand guidelines",
  },
  IT: {
    "general.clear-all": "Rimuovi filtri",
    "general.sort": "Ordine",
    "general.showing-results": "Visualizzazione di %results% su %total% risultati",
    "general.skip-to-main-content": "Passa al contenuto principale",
    "select.language-placeholder": "Scegli la tua lingua",
    "select.no-options-message": "Lingua non disponibile",
    "select.default": "Selezionare",
    "blog.try-free.body": "Prova Databricks gratis",
    "blog.try-free.cta": "Comincia",
    "footer.language.title": "Mondo",
    "form.first-name": "Nome",
    "form.last-name": "Cognome",
    "form.full-name": "Nome completo",
    "form.company": "Azienda",
    "form.company-email": "E-mail aziendale",
    "form.country": "Nazione",
    "form.phone": "Telefono",
    "form.phone-optional": "Telefono (Optional)",
    "form.contact-reason": "Motivo della richiesta",
    "form.contact-sales": "Contatta il reparto Vendite",
    "form.databricks-products-features-and-capabilities":
      "Prodotti e funzionalità di Databricks",
    "form.technical-support-for-existing-customers":
      "Assistenza tecnica per clienti attivi",
    "form.events-and-webinars": "Eventi e webinar",
    "form.press-analyst-inquiry": "Richiesta stampa/analisti",
    "form.training-courses-and-certification":
      "Corsi di formazione e certificazione",
    "form.request-demo": "Richiedi una demo",
    "form.job-title": "Titolo professionale",
    "form.title": "Titolo professionale",
    "form.where-do-you-intend-to-run-your-analytic-workloads?":
      "Dove intendi eseguire i carichi di lavoro di analisi?",
    "form.aws": "AWS",
    "form.azure": "Azure",
    "form.google-cloud-platform": "Piattaforma Google Cloud",
    "form.on-premise": "On premise",
    "form.other": "Altro",
    "form.message": "Messaggio",
    "form.keep-me-informed-with-occasional-updates-about-databricks-and-related-open-source-products":
      "Voglio ricevere informazioni sugli aggiornamenti di Databricks e sui relativi prodotti open-source",
    "form.submit": "invia",
    "form.please-wait": "attendi",
    "form.select": "Si prega di selezionare",
    "form.this-field-is-required": "Campo obbligatorio.",
    "form.must-be-valid-email.": "Si prega di inserire un indirizzo email valido.",
    "form.get-started": "Get Started",
    "form.choose-a-cloud-provider": "Seleziona un fornitore di servizi cloud",
    "pricing.plan.selector": "Seleziona un piano",
    "pricing.plan.helper": "aiutami a scegliere",
    "pricing.plan.standard": "Standard",
    "pricing.plan.premium": "Premium",
    "pricing.plan.enterprise": "Enterprise",
    "pricing.cloud.selector": "Seleziona un cloud",
    "pricing.cloud.azure": "Azure",
    "pricing.cloud.aws": "AWS",
    "pricing.cloud.gcp": "Google Cloud",
    "pricing.region.selector": "Seleziona una regione",
    "pricing.region.selector.description":
      "(fare riferimento alle FAQ qui sotto per la disponibilità del prodotto)",
    "pricing.region.serverless": "Area geografica con SQL serverless e SQL Pro",
    "pricing.region.us-east": "US East (N. Virginia)",
    "pricing.region.us-east-2": "US East (Ohio)",
    "pricing.region.us-west": "US West (Oregon)",
    "pricing.region.europe": "Europa (Francoforte)",
    "pricing.region.europe-2": "Europa (Irlanda)",
    "pricing.region.apac": "AP (Sydney)",
    "form.form-title": "Crea il tuo account Databricks",
    "form.submit-text": "Continuare",
    "form.error-required": "Campo obbligatorio.",
    "form.error-loading": "Caricamento in corso...",
    "form.error-error": "Si è verificato un errore. Riprova più tardi.",
    "form.error-email-error":
      "Impossibile creare un account con l'indirizzo e-mail fornito. Se hai già usato questo indirizzo e-mail in passato, prova il meccanismo di recupero della password sulla <a href='https://accounts.cloud.databricks.com/registration.html#login'>pagina di accesso</a> di Databricks, oppure <a href='https://www.databricks.com/it/company/contact'>contatta il nostro team di vendita</a> per assistenza.",
    "form.error-field-phone": "Inserire un numero di telefono valido",
    "form.error-field-email": "Inserire un indirizzo e-mail valido",
    "form.cumminity-edition-title": "Non hai un account cloud?",
    "form.cumminity-edition-text":
      "La Community Edition è un ambiente Databricks con funzionalità limitate per uso personale e di formazione.",
    "form.cumminity-edition-get-started":
      "Comincia a utilizzare la Community Edition",
    "form.cumminity-edition-get-started-agreement":
      "Cliccando su Comincia a utilizzare la Community Edition, accetti la ",
    "form.and": "e",
    "form.privacy-policy": "Politica di riservatezza",
    "form.terms-of-service": "i Termini di servizio",
    "form.get-started-agreement": "Cliccando su “Comincia”, accetti la ",
    "partners.load-more": "CARICA ALTRI",
    "partners.filters.region": "Regione",
    "partners.filters.use-cases": "Casi d'uso",
    "partners.filters.partner": "Partner",
    "general.explore-the-case-study": "Esplora il caso di studio",
    "general.learn-more": "Maggiori informazioni",
    "general.youtube-privacy-accept":
      "Per riprodurre questo video, fare clic qui e accettare i cookie",
    "glossary.back-to-glossary": "Torna al Glossario",
    "glossary.additional-resources": "Risorse aggiuntive",
    "research.filter.research-domain": "Dominio di ricerca",
    "resources-overview.resource-type": "Tipo di risorsa",
    "card.featured": "In primo piano",
    "general.search": "ricerca",
    "demo.filters.product": "Prodotto",
    "demo.filters.demo-type": "Tipo di demo",
    "general.newest": "Più recente",
    "general.subscribe-to-newsletter": "Iscriviti alla Newsletter",
    "card.tag.recommended": "consigliato",
    "pdf.error": "Impossibile caricare il file PDF.",
    "featured.stories": "Featured Stories",
    "more.headlines": "More Headlines",
    "press.releases": "Press Releases",
    "press.releases.see.all": "See all press releases",
    "press.releases.see.more": "See more",
    "resources.title": "Resources",
    "resources.contact.title": "Contact",
    "resources.inquires": "For press inquires:",
    "resources.stay.connected": "Stay connected",
    "resources.stay.connected.description":
      "Stay up to date and connect with us through our newsletter, social media channels and blog RSS feed.",
    "resources.subscribe": "Subscribe to the newsletter",
    "resources.get": "Get assets",
    "resources.contact.description":
      "If you would like to use Databricks materials, please contact <u><a href='mailto: brand@databricks.com'>brand@databricks.com</a></u> and provide the following information:",
    "resources.contact.info":
      "Your name and title<br />Company name and location<br />Description of request",
    "resources.contact.guidelines": "View brand guidelines",
  },
  JA: {
    "general.skip-to-main-content": "メインコンテンツへジャンプ",
    "select.language-placeholder": "言語を選択してください",
    "select.no-options-message": "利用できない言語",
    "select.default": "選択する",
    All: "すべて",
    Blog: "ブログ",
    "general.search": "検索",
    "general.newest": "最新",
    "general.next": "次へ",
    "general.previous": "Previous",
    "general.all": "全て",
    "general.page-number": "ページ %pageNumber%",
    "general.clear-all": "すべてクリア",
    "general.sort": "選別",
    "general.showing-results": "%total% の結果のうち %results% を表示しています",
    "list.separator": "、",
    "list.last-separator": "、",
    "blog.seo.title": "Databricks ブログ",
    "blog.seo.description":
      "Databricks チームから製品のアップデート、Apache Spark のベストプラクティス、ユースケースなどを入手してください。",
    "blog.head.author-prefix": "",
    "blog.head.author-suffix": " による投稿",
    "blog.related.title": "関連記事",
    "blog.try-free.body": "Databricks 無料トライアル",
    "blog.try-free.cta": "使ってみる",
    "blog.category.empty":
      "このカテゴリーにはブログはありません。他のカテゴリーを選択してください。",
    "footer.language.title": "言語地域",
    "form.first-name": "お名前（名)",
    "form.last-name": "お名前（姓)",
    "form.full-name": "お名前（フルネーム)",
    "form.company": "企業／団体名",
    "form.company-email": "業務用メールアドレス",
    "form.country": "国名",
    "form.phone": "電話番号",
    "form.phone-optional": "電話番号（任意)",
    "form.contact-reason": "お問い合わせの目的",
    "form.contact-sales": "営業へのご連絡",
    "form.databricks-products-features-and-capabilities": "Databricks の製品、機能",
    "form.technical-support-for-existing-customers": "技術サポート（既存のお客様)",
    "form.events-and-webinars": "イベント、Web セミナー",
    "form.press-analyst-inquiry": "メディア、アナリスト関連",
    "form.training-courses-and-certification": "トレーニング、認定プログラム",
    "form.request-demo": "デモのご用命",
    "form.job-title": "役職名",
    "form.title": "役職名",
    "form.where-do-you-intend-to-run-your-analytic-workloads?":
      "分析ワークロードの実行環境（予定を含む)",
    "form.aws": "AWS",
    "form.azure": "Azure",
    "form.google-cloud-platform": "Google Cloud",
    "form.on-premise": "オンプレミス",
    "form.other": "その他",
    "form.message": "お問い合わせ内容の詳細",
    "form.keep-me-informed-with-occasional-updates-about-databricks-and-related-open-source-products":
      "Databricks および関連するオープンソースの製品についての最新情報を受け取る",
    "form.submit": "送信",
    "form.please-wait": "お待ちください",
    "form.select": "選択してください",
    "form.this-field-is-required": "必須項目です。",
    "form.must-be-valid-email.": "有効なメール アドレスを入力してください",
    "form.get-started": "Get Started",
    "form.choose-a-cloud-provider": "クラウドプロバイダを選択してください。",
    "pricing.plan.selector": "プランを選択",
    "pricing.plan.helper": "選択を手伝ってください",
    "pricing.plan.standard": "スタンダード",
    "pricing.plan.premium": "プレミアム",
    "pricing.plan.enterprise": "エンタープライズ",
    "pricing.cloud.selector": "クラウドを選択",
    "pricing.cloud.azure": "Azure",
    "pricing.cloud.aws": "AWS",
    "pricing.cloud.gcp": "Google Cloud",
    "pricing.region.selector": "地域を選択",
    "pricing.region.selector.description": "(製品の在庫については、以下のFAQを参照)",
    "pricing.region.serverless": "サーバーレス SQL & SQL Pro を使用したリージョン",
    "pricing.region.us-east": "US East (バージニア州北部)",
    "pricing.region.us-east-2": "US East (オハイオ州)",
    "pricing.region.us-west": "US West (オレゴン州)",
    "pricing.region.europe": "Europe (フランクフルト)",
    "pricing.region.europe-2": "Europe (アイルランド)",
    "pricing.region.apac": "AP (シドニー)",
    "form.form-title": "Databricks アカウントを作成する",
    "form.submit-text": "続ける",
    "form.error-required": "必須項目です。",
    "form.error-loading": "読み込み中…",
    "form.error-error":
      "エラーが発生しました。しばらくたってから再度お試しください。",
    "form.error-email-error":
      "入力されたメールアドレスではアカウントを作成できません。このメールアドレスを過去に使用された場合は、Databricks の<a href='https://accounts.cloud.databricks.com/registration.html#login'>ログインページ</a>で “Forgot Password?” をお試しいただくか、または、<a href='https://www.databricks.com/jp/company/contact'>ご相談・お問い合わせ</a> のページをご利用ください",
    "form.error-field-phone": "有効な電話番号を入力してください。",
    "form.error-field-email": "有効なメールアドレスを入力してください。",
    "form.cumminity-edition-title": "クラウドのアカウントをお持ちでないお客様",
    "form.cumminity-edition-text":
      "コミュニティ版は、個人的な使用やトレーニングのための限定的な Databricks 環境です。",
    "form.cumminity-edition-get-started": "コミュニティ版を使ってみる",
    "form.cumminity-edition-get-started-agreement":
      "「コミュニティ版を使ってみる」をクリックすることで、 ",
    "form.and": "と",
    "form.privacy-policy": "プライバシーポリシー",
    "form.terms-of-service": "利用規約",
    "form.get-started-agreement":
      "上のボタンをクリックして送信することで、Databricks の ",
    "form.get-started-agreement-end": "に同意したものとみなされます",
    "partners.load-more": "もっと見る",
    "partners.filters.region": "リージョン",
    "partners.filters.use-cases": "ユースケース",
    "partners.filters.partner": "パートナー",
    "general.explore-the-case-study": "導入事例を見る",
    "general.learn-more": "詳しく見る",
    "glossary.back-to-glossary": "用語集に戻る",
    "glossary.additional-resources": "関連資料",
    "general.youtube-privacy-accept":
      "このビデオを再生するには、ここをクリックして Cookie を受け入れてください",
    "research.filter.research-domain": "研究領域",
    "resources-overview.resource-type": "リソースの種類",
    "card.featured": "特徴",
    "demo.filters.product": "積",
    "demo.filters.demo-type": "デモタイプ",
    "general.subscribe-to-newsletter": "ニュースレターを購読する",
    "card.tag.recommended": "推奨",
    "pdf.error": "PDFファイルの読み込みに失敗しました。",
    "featured.stories": "特集記事",
    "more.headlines": "ニュース記事",
    "press.releases": "プレスリリース",
    "press.releases.see.all": "全てのプレスリリースを見る",
    "press.releases.see.more": "もっと見る",
    "resources.title": "関連リソース",
    "resources.contact.title": "Contact",
    "resources.inquires": "For press inquires:",
    "resources.stay.connected": "Stay connected",
    "resources.stay.connected.description":
      "Stay up to date and connect with us through our newsletter, social media channels and blog RSS feed.",
    "resources.subscribe": "Subscribe to the newsletter",
    "resources.get": "Get assets",
    "resources.contact.description":
      "If you would like to use Databricks materials, please contact <u><a href='mailto: brand@databricks.com'>brand@databricks.com</a></u> and provide the following information:",
    "resources.contact.info":
      "Your name and title<br />Company name and location<br />Description of request",
    "resources.contact.guidelines": "View brand guidelines",
    "general.others": "その他",
  },
  KO: {
    "general.clear-all": "모두 지우기",
    "general.sort": "정렬 기준",
    "general.showing-results": "%total% 결과 중 %results% 표시 중",
    "select.language-placeholder": "언어 선택",
    "select.no-options-message": "언어를 사용할 수 없음",
    "general.skip-to-main-content": "주요 컨텐츠로 이동",
    "select.default": "선택하다",
    All: "모두",
    "list.last-separator": ", ",
    "blog.head.author-prefix": `작성자: `,
    "blog.head.share": `이 포스트 공유하기`,
    "blog.related.title": "관련 포스트",
    "blog.try-free.body": "Databricks 무료로 시작하기",
    "blog.try-free.cta": "시작하기",
    "blog.seo.title": "Databricks 블로그",
    "blog.seo.description":
      "Databricks 팀으로부터 제품 업데이트, Apache Spark 베스트 프랙티스, 사용 사례 등을 받아보세요.",
    "form.first-name": "이름",
    "form.last-name": "성",
    "form.full-name": "성명",
    "form.company": "회사",
    "form.company-email": "회사 이메일",
    "form.country": "국가",
    "form.phone": "전화번호",
    "form.phone-optional": "전화번호(선택사항)",
    "form.contact-reason": "문의 이유",
    "form.contact-sales": "영업팀 문의",
    "form.databricks-products-features-and-capabilities":
      "Databricks 제품, 특징 및 기능",
    "form.technical-support-for-existing-customers": "기존 고객 기술 지원",
    "form.events-and-webinars": "이벤트 및 웨비나",
    "form.press-analyst-inquiry": "언론/애널리스트 문의",
    "form.training-courses-and-certification": "교육 강좌 및 인증",
    "form.request-demo": "데모 요청",
    "form.job-title": "직함",
    "form.title": "직함",
    "form.where-do-you-intend-to-run-your-analytic-workloads?":
      "다음 중 귀사 분석 워크로드를 실행하려는 위치는 어디입니까?",
    "form.aws": "AWS",
    "form.azure": "AZURE",
    "form.google-cloud-platform": "Google Cloud Platform",
    "form.on-premise": "온프레미스",
    "form.other": "기타",
    "form.message": "메시지",
    "form.keep-me-informed-with-occasional-updates-about-databricks-and-related-open-source-products":
      "Databricks 및 관련 오픈소스 제품에 관해 업데이트 소식이 있을 때 받아보겠습니다.",
    "form.submit": "제출하다",
    "form.please-wait": "기다리세요",
    "form.select": "보기 중에서 선택하세요",
    "form.this-field-is-required": "이 필드는 필수 항목입니다.",
    "form.must-be-valid-email.": "유효한 이메일 주소를 입력하세요",
    "form.get-started": "Get Started",
    "form.choose-a-cloud-provider": "클라우드 제공업체 선택",
    "pricing.plan.selector": "플랜 선택",
    "pricing.plan.helper": "선택 도움말",
    "pricing.plan.standard": "Standard",
    "pricing.plan.premium": "Premium",
    "pricing.plan.enterprise": "Enterprise",
    "pricing.cloud.selector": "클라우드 선택",
    "pricing.cloud.azure": "Azure",
    "pricing.cloud.aws": "AWS",
    "pricing.cloud.gcp": "Google Cloud",
    "pricing.region.selector": "리전 선택",
    "pricing.region.selector.description": "(제품 사용 가능 여부는 아래 FAQ 참조)",
    "pricing.region.serverless": "서버리스 SQL 및 SQL Pro가 있는 지역",
    "pricing.region.us-east": "미국 동부(버지니아 북부)",
    "pricing.region.us-east-2": "미국 동부(오하이오)",
    "pricing.region.us-west": "미국 서부(오레곤)",
    "pricing.region.europe": "EU (프랑크푸르트)",
    "pricing.region.europe-2": "EU (아일랜드)",
    "pricing.region.apac": "아시아 태평양 (시드니)",
    "form.form-title": "Databricks 계정 생성하기",
    "form.submit-text": "계속하다",
    "form.error-required": "이 필드는 필수 항목입니다.",
    "form.error-loading": "로드 중...",
    "form.error-error": "오류가 발생했습니다. 나중에 다시 시도하세요.",
    "form.error-email-error":
      "제공하신 이메일로 계정을 생성할 수 없습니다. 이전에 이 이메일을 사용했거나 Databricks 비밀번호 메커니즘을 잊으신 경우 Databricks <a href='https://accounts.cloud.databricks.com/registration.html#login'>로그인 페이지</a> 또는 <a href='https://www.databricks.com/company/contact'>영업 팀에 문의</a> 에서 도움을 받으세요.",
    "form.error-field-phone": "올바른 전화번호를 ㅇ비력하세요",
    "form.error-field-email": "올바른 이메일 주소를 입력하세요",
    "form.cumminity-edition-title": "클라우드 계정이 없으신가요?",
    "form.cumminity-edition-text":
      "커뮤니티 에디션은 개인 및 교육 용도로 제한된 Databricks 환경입니다.",
    "form.cumminity-edition-get-started": "커뮤니티 에디션으로 시작하기",
    "form.cumminity-edition-get-started-agreement":
      "“커뮤니티 에디션으로 시작하기”를 클릭하면 ",
    "form.and": "및",
    "form.privacy-policy": "개인정보 보호 정책",
    "form.terms-of-service": "서비스 약관",
    "form.get-started-agreement": "“시작하기”를 클릭하면 ",
    "form.get-started-agreement-end": "에 동의하게 됩니다",
    "partners.load-more": "자세히 보기",
    "partners.filters.region": "지역",
    "partners.filters.use-cases": "사용 사례",
    "partners.filters.partner": "파트너",
    "general.explore-the-case-study": "사례 연구 살펴보기",
    "general.learn-more": "자세히",
    "glossary.back-to-glossary": "용어집으로 돌아가기",
    "glossary.additional-resources": "추가 자료",
    "general.youtube-privacy-accept":
      "이 비디오를 재생하려면 여기를 클릭하고 쿠키를 수락하십시오",
    "research.filter.research-domain": "연구영역",
    "resources-overview.resource-type": "리소스 유형",
    "card.featured": "추천",
    "general.search": "검색",
    "demo.filters.product": "제품",
    "demo.filters.demo-type": "데모 유형",
    "general.newest": "최신",
    "general.subscribe-to-newsletter": "뉴스레터 구독하기",
    "card.tag.recommended": "추천",
    "pdf.error": "PDF 파일을 로드하지 못했습니다.",
    "featured.stories": "Featured Stories",
    "more.headlines": "More Headlines",
    "press.releases": "Press Releases",
    "press.releases.see.all": "See all press releases",
    "press.releases.see.more": "See more",
    "resources.title": "Resources",
    "resources.contact.title": "Contact",
    "resources.inquires": "For press inquires:",
    "resources.stay.connected": "Stay connected",
    "resources.stay.connected.description":
      "Stay up to date and connect with us through our newsletter, social media channels and blog RSS feed.",
    "resources.subscribe": "Subscribe to the newsletter",
    "resources.get": "Get assets",
    "resources.contact.description":
      "If you would like to use Databricks materials, please contact <u><a href='mailto: brand@databricks.com'>brand@databricks.com</a></u> and provide the following information:",
    "resources.contact.info":
      "Your name and title<br />Company name and location<br />Description of request",
    "resources.contact.guidelines": "View brand guidelines",
    "general.others": "다른 사람",
  },
  BR: {
    "general.skip-to-main-content": "Ir para o conteúdo principal",
    "select.language-placeholder": "Escolha seu idioma",
    "select.no-options-message": "Idioma não disponíve",
    "select.default": "Selecione",
    All: "Todos",
    Blog: "Blog",
    "list.separator": ", ",
    "list.last-separator": " e ",
    "general.next": "Próximo",
    "general.all": "Todos",
    "general.previous": "Anterior",
    "general.page-number": "Página %pageNumber%",
    "general.page": "Página",
    "general.home": "Casa",
    "general.showing-results": "Exibição %results% of %total% resultados",
    "general.showing-customers": "Exibição %results% of %total% clientes",
    "general.no-results-filters":
      "Não há resultados disponíveis. Tente ajustar os filtros ou inicie uma nova pesquisa.",
    "general.reset-list": "redefinir a lista",
    "general.clear-all": "Apagar tudo",
    "general.sort": "Ordenar",
    "general.industry": "Indústria",
    "general.region": "Região",
    "general.platform": "Platform",
    "general.product": "Product",
    "general.cloud": "Cloud",
    "general.solution": "Solução",
    "general.tech-partner": "Parceiro Tecnológico",
    "blog.seo.title": "O Blog Databricks",
    "blog.seo.description":
      "Obtenha atualizações de produtos, práticas recomendadas do Apache Spark, casos de uso e muito mais da equipe do Databricks.",
    "blog.related.title": "Artigos relacionados",
    "blog.related.cta": "Ver tudo %category% posts",
    "blog.try-free.body": "Experimente o Databricks gratuitamente",
    "blog.try-free.cta": "Introdução",
    "blog.head.author-prefix": "por ",
    "blog.head.author-suffix": "",
    "blog.head.meta": "em",
    "blog.head.share": "Compartilhe este post",
    "blog.category.empty":
      "Não há blogs nesta categoria. Selecione outra categoria.",
    "footer.language.title": "Mundial",
    "legal.header": "Legal",
    "form.first-name": "Primeiro Nome",
    "form.last-name": "Segundo Nome",
    "form.full-name": "Nome Completo",
    "form.company": "Empresa",
    "form.company-email": "Email",
    "form.country": "País",
    "form.phone": "Telefone",
    "form.phone-optional": "Telefone (Opcional)",
    "form.contact-reason": "Motivo do Contato",
    "form.contact-sales": "Contato Comercial",
    "form.databricks-products-features-and-capabilities":
      "Produtos e Funcionalidades Databricks",
    "form.technical-support-for-existing-customers":
      "Suporte Técnico para Clientes existentes",
    "form.events-and-webinars": "Eventos e Webinars",
    "form.press-analyst-inquiry": "Imprensa / Analista",
    "form.training-courses-and-certification":
      "Cursos de Treinamentos e Certificações",
    "form.request-demo": "Solicitar uma Demo",
    "form.job-title": "Cargo",
    "form.title": "Título",
    "form.where-do-you-intend-to-run-your-analytic-workloads?":
      "Onde você pretende executar seus workloads analíticos?",
    "form.aws": "AWS",
    "form.azure": "Azure",
    "form.google-cloud-platform": "Google Cloud Platform",
    "form.on-premise": "On-Premise",
    "form.other": "Outros",
    "form.message": "Mensagem",
    "form.keep-me-informed-with-occasional-updates-about-databricks-and-related-open-source-products":
      "Me mantenha informado sobre Databricks e produtos open source relacionados",
    "form.submit": "Enviar",
    "form.please-wait": "Aguardar",
    "form.select": "Selecionar",
    "form.this-field-is-required": "Campo obrigatório",
    "form.must-be-valid-email.": "Precisar ser um email válido.",
    "form.get-started": "Comece",
    "form.choose-a-cloud-provider": "Escolha um provedor de cloud",
    "customer.taxonomy.industry": "INDÚSTRIA:",
    "customer.taxonomy.platform": "CASO DE USO DA PLATAFORMA:",
    "customer.taxonomy.cloud": "CLOUD:",
    "pricing.plan.selector": "Selecionar plano",
    "pricing.plan.helper": "ajude-me a escolher",
    "pricing.plan.standard": "Standard",
    "pricing.plan.premium": "Premium",
    "pricing.plan.enterprise": "Enterprise",
    "pricing.cloud.selector": "Selecione a cloud",
    "pricing.cloud.azure": "Azure",
    "pricing.cloud.aws": "AWS",
    "pricing.cloud.gcp": "Google Cloud",
    "pricing.region.selector": "Selecionar região",
    "pricing.region.selector.description":
      "(consulte as perguntas frequentes abaixo para saber a disponibilidade do produto)",
    "pricing.region.serverless": "região com SQL e SQL Pro sem servidor",
    "pricing.region.us-east": "US East (N. Virginia)",
    "pricing.region.us-east-2": "US East (Ohio)",
    "pricing.region.us-west": "US West (Oregon)",
    "pricing.region.europe": "Europe (Frankfurt)",
    "pricing.region.europe-2": "Europe (Ireland)",
    "pricing.region.apac": "AP (Sydney)",
    "customer.taxonomy.solution": "SOLUÇÃO:",
    "form.form-title": "Crie sua conta Databricks",
    "form.submit-text": "Continuar",
    "form.error-required": "Campo obrigatório",
    "form.error-loading": "Carregando...",
    "form.error-error": "Ocorreu um erro, por favor, tente mais tarde.",
    "form.error-email-error":
      "Não foi possível criar uma conta com o email informado. Se você utilizou este email no passado, tente o mecanismo de esqueci minha senha na <a href='https://accounts.cloud.databricks.com/registration.html#login'>página de login</a> da Databricks ou <a href='https://www.databricks.com/br/company/contact'>entre em contato com nosso time de vendas</a> para ajuda.",
    "form.error-field-phone": "Por favor, insira um número de telefone válido",
    "form.error-field-email": "Por favor, insira um endereço de email válido",
    "form.cumminity-edition-title": "Não tem uma conta de nuvem?",
    "form.cumminity-edition-text":
      "A Community Edition é um ambiente Databricks limitado para uso pessoal e treinamentos.",
    "form.cumminity-edition-get-started": "Comece a utilizar a Community Edition",
    "form.cumminity-edition-get-started-agreement":
      'Ao clicar em "Comece a utilizar a Community Edition," você concorda com a',
    "form.and": "e",
    "form.privacy-policy": "Política de privacidade",
    "form.terms-of-service": "Termos de Serviço",
    "form.get-started-agreement": 'Ao clicar em "Iniciar" você concorda com a ',
    "partners.load-more": "Carregue mais",
    "partners.filters.region": "região",
    "partners.filters.use-cases": "Casos de utilização",
    "partners.filters.partner": "Parceiro",
    "general.explore-the-case-study": "Explore o estudo de caso",
    "general.learn-more": "Saiba mais",
    "general.youtube-privacy-accept":
      "Para reproduzir este vídeo, clique aqui e aceite os cookies",
    "glossary.back-to-glossary": "Voltar ao glossário",
    "glossary.additional-resources": "Recursos adicionais",
    "research.filter.research-domain": "Domínio de Pesquisa",
    "resources-overview.resource-type": "Tipo de recurso",
    "card.featured": "Destacado",
    "general.search": "procurar",
    "demo.filters.product": "Produto",
    "demo.filters.demo-type": "Tipo de demonstração",
    "general.newest": "Mais recente",
    "general.subscribe-to-newsletter": "Subscrever a Newsletter",
    "card.tag.recommended": "Recomendado",
    "pdf.error": "Falha ao carregar o arquivo PDF.",
    "featured.stories": "Featured Stories",
    "more.headlines": "More Headlines",
    "press.releases": "Press Releases",
    "press.releases.see.all": "See all press releases",
    "press.releases.see.more": "See more",
    "resources.title": "Resources",
    "resources.contact.title": "Contact",
    "resources.inquires": "For press inquires:",
    "resources.stay.connected": "Stay connected",
    "resources.stay.connected.description":
      "Stay up to date and connect with us through our newsletter, social media channels and blog RSS feed.",
    "resources.subscribe": "Subscribe to the newsletter",
    "resources.get": "Get assets",
    "resources.contact.description":
      "If you would like to use Databricks materials, please contact <u><a href='mailto: brand@databricks.com'>brand@databricks.com</a></u> and provide the following information:",
    "resources.contact.info":
      "Your name and title<br />Company name and location<br />Description of request",
    "resources.contact.guidelines": "View brand guidelines",
  },
}

const useTranslate = () => {
  const { currentLanguage, defaultLanguage } = useLanguageContext()

  const translate = (key, tokens) => {
    const translation =
      typeof translations?.[currentLanguage?.id]?.[key] === "string"
        ? translations[currentLanguage.id][key]
        : translations?.[defaultLanguage.id]?.[key]

    const parsedTranslation = translation?.split(/(%.+?%)/g).map((token) => {
      if (!token.startsWith("%")) {
        return token
      }

      const tokenName = token.slice(1, -1)
      const tokenValue = tokens?.[tokenName]

      return tokenValue || token
    })

    return parsedTranslation
  }

  const translateList = (list) => {
    if (!(list?.length > 1) || typeof list === "string") {
      return list
    }

    const newList = []

    list?.forEach((element, index) => {
      if (index === 0) {
        newList.push(element)
        return
      }

      if (index === list.length - 1) {
        newList.push(translate("list.last-separator"), element)
        return
      }

      newList.push(translate("list.separator"), element)
    })

    return newList
  }

  return { translate, translateList }
}

export default useTranslate
