import React from "react"
import PropTypes from "prop-types"
import {
  Facebook,
  FacebookRounded,
  Glassdoor,
  Close,
  MenuBars,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  LinkedIn,
  Rss,
  Twitter,
  Youtube,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowRightThin,
  ArrowUp,
  Geospatial,
  Minus,
  Plus,
  Search,
  Sort,
  AcceleratorDatabricks,
  AcceleratorPartner,
  Energy,
  Financial,
  Media,
  Healthcare,
  Hourglass,
  Retail,
  Manufacturing,
  PublicSector,
  LogoSeparator,
  Technology,
  Refresh,
  MaliciousDocument,
  Dot,
  Vector,
  UnifiedData,
  PartnerSolutions,
  AccelerateOutcomes,
  Collaboration,
  FacebookCircle,
  Play,
  Pause,
  ArrowDrop,
  Quote,
  Dbce,
  Checked,
  CheckboxEmpty,
  Ellipses,
  RadioEnabled,
  RadioDisabled,
  HelpIcon,
  TranscriptPlay,
  TranscriptPlayActive,
  PlusCircle,
  MinusCircle,
  Gaming,
  Streaming,
  AdvertisingMarketing,
  LinkArrow,
  PauseMotion,
  PlayMotion,
  CheckedCircle,
  Language,
  SearchNav,
  Circle,
  CircleFailed,
  EmptyCircle,
  DatabricksLoading,
  Lock,
  CircleCheckmark,
  CircledHyphen,
} from "./CustomIcons"

const iconsMap = {
  facebook: Facebook,
  facebookRounded: FacebookRounded,
  glassdoor: Glassdoor,
  linkedIn: LinkedIn,
  close: Close,
  menuBars: MenuBars,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  rss: Rss,
  twitter: Twitter,
  youtube: Youtube,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowRightThin: ArrowRightThin,
  arrowUp: ArrowUp,
  geospatial: Geospatial,
  minus: Minus,
  plus: Plus,
  acceleratorDb: AcceleratorDatabricks,
  acceleratorPartner: AcceleratorPartner,
  search: Search,
  sort: Sort,
  energy: Energy,
  financial: Financial,
  media: Media,
  healthcare: Healthcare,
  hourglass: Hourglass,
  retail: Retail,
  manufacturing: Manufacturing,
  publicSector: PublicSector,
  technology: Technology,
  refresh: Refresh,
  maliciousDocument: MaliciousDocument,
  logoSeparator: LogoSeparator,
  dot: Dot,
  vector: Vector,
  unifiedData: UnifiedData,
  partnerSolutions: PartnerSolutions,
  accelerateOutcomes: AccelerateOutcomes,
  collaboration: Collaboration,
  facebookCircle: FacebookCircle,
  play: Play,
  pause: Pause,
  arrowDrop: ArrowDrop,
  quote: Quote,
  dbce: Dbce,
  checked: Checked,
  checkboxEmpty: CheckboxEmpty,
  ellipses: Ellipses,
  radioEnabled: RadioEnabled,
  radioDisabled: RadioDisabled,
  help: HelpIcon,
  transcriptPlay: TranscriptPlay,
  transcriptPlayActive: TranscriptPlayActive,
  plusCircle: PlusCircle,
  minusCircle: MinusCircle,
  gaming: Gaming,
  streaming: Streaming,
  advertisingMarketing: AdvertisingMarketing,
  linkArrow: LinkArrow,
  pauseMotion: PauseMotion,
  playMotion: PlayMotion,
  checkedCircle: CheckedCircle,
  language: Language,
  searchNav: SearchNav,
  circle: Circle,
  circleFailed: CircleFailed,
  emptyCircle: EmptyCircle,
  databricksLoading: DatabricksLoading,
  lock: Lock,
  circleCheckmark: CircleCheckmark,
  circledHyphen: CircledHyphen,
}

const IconResolver = ({ token, className, ...props }) => {
  const Icon = iconsMap[token]
  if (!Icon) {
    return <></>
  }
  return <Icon className={className} {...props} />
}

IconResolver.propTypes = {
  token: PropTypes.oneOf([
    "facebook",
    "facebookRounded",
    "glassdoor",
    "linkedIn",
    "close",
    "menuBars",
    "chevronDown",
    "chevronLeft",
    "chevronRight",
    "rss",
    "twitter",
    "youtube",
    "arrowDown",
    "arrowLeft",
    "arrowRight",
    "arrowRightThin",
    "arrowUp",
    "geospatial",
    "plus",
    "minus",
    "acceleratorDb",
    "acceleratorPartner",
    "search",
    "sort",
    "energy",
    "financial",
    "media",
    "healthcare",
    "hourglass",
    "retail",
    "manufacturing",
    "publicSector",
    "technology",
    "refresh",
    "maliciousDocument",
    "dot",
    "logoSeparator",
    "vector",
    "unifiedData",
    "partnerSolutions",
    "accelerateOutcomes",
    "collaboration",
    "facebookCircle",
    "play",
    "pause",
    "arrowDrop",
    "quote",
    "dbce",
    "checked",
    "checkboxEmpty",
    "ellipses",
    "help",
    "transcriptPlay",
    "transcriptPlayActive",
    "plusCircle",
    "minusCircle",
    "gaming",
    "streaming",
    "advertisingMarketing",
    "linkArrow",
    "pauseMotion",
    "playMotion",
    "checkedCircle",
    "language",
    "searchNav",
    "circle",
    "circleFailed",
    "emptyCircle",
    "databricksLoading",
    "circleCheckmark",
    "circledHyphen",
  ]).isRequired,
  className: PropTypes.string,
}

IconResolver.defaultProps = {
  className: "",
}

export default IconResolver
